### PR TITLE
Migrate to 7.1.0

### PR DESCRIPTION
**Pull request by JohannaOtt**

### CODE REVIEW

**Review by florianesser — CHANGES_REQUESTED** [review]
@JohannaOtt Quick first feedback: please don't use paths with spaces in it. If we want to create a new path hierarchy for the 7.1 alignments (e.g. `mappings-7.1`), we should also rename the folder `mappings` to `mappings-6.0` then.

**Comment by JohannaOtt** [comment]
@florianesser Ok, maybe we can talk about the overall structure in our meeting on Thursday so that we have it ready once the migration will be ordered.

**Comment by JohannaOtt** [comment]
@florianesser Just realized that the paths to the base alignment need to be changed in all alignment.xml files. So this one should not be approved/merged yet.

**Comment by JohannaOtt** [comment]
@florianesser I changed the paths to the base alignment where necessary - review can be continued

**Comment by florianesser** [comment]
@JohannaOtt The paths in `projects.yaml` also need to be adapted to the new folder structure. There is also a reference in `build.gradle` to the previous folder name `mappings` which needs to be updated.

In `mappings7.1/Hydrography/aaa-hy-p.halex`, the `AX_Meer` to `LandWaterBoundary` mapping cell is disabled, is that intended?

The source test data loaded in that project doesn't seem to match the source schema. Would it make sense to add 7.1 test data to the `testdaten` folder and load that instead?

**Comment by JohannaOtt** [comment]
> The paths in projects.yaml also need to be adapted to the new folder structure. There is also a reference in build.gradle to the previous folder name mappings which needs to be updated.

Done


> In mappings7.1/Hydrography/aaa-hy-p.halex, the AX_Meer to LandWaterBoundary mapping cell is disabled, is that intended?

There is the note "Die Abbildung ist deaktiviert, da eien geometrische Verschneidung/Analyse notwendig ist, um aus den flächenhaften Ausgangsgeometrien die korrekten linienhfaten Berührungsgeometrien abzuleiten." attached to the cell, so I'd say yes.


> The source test data loaded in that project doesn't seem to match the source schema. Would it make sense to add 7.1 test data to the testdaten folder and load that instead?

I removed the source data from the transformation project as the they are usually saved without source data and added it to the testdaten folder.

**Review by florianesser — APPROVED** [review]
LGTM

**Pull request merged**
