### PR TITLE
Remove60

### PR DESCRIPTION
**Pull request by JohannaOtt**
SVC-1724

### CODE REVIEW

**Review by florianesser — CHANGES_REQUESTED** [review]
@JohannaOtt It looks like several `.halez` files and extracted folders were added here that should not be added to the repository. 

Also, please check `projects.yaml` as well as `transformations.yaml` and remove transformations that don't exist anymore in 7.1 (e.g. `annex-1/Addresses/aaa-ad-01.halex`). It can be tested by checking that `./gradlew tasks` runs without errors.

**Comment by JohannaOtt** [comment]
> It looks like several .halez files and extracted folders were added here that should not be added to the repository.

Good catch, thank you. Removed them.


>  It can be tested by checking that ./gradlew tasks runs without errors.

It does not yet run without errors because the ALKIS2INSPIRE_ELU.halex is still missing. It is expected to be added once the tasks for [this project](https://haleconnect.com/#/transformation/org/765/9e2f27b8-5606-4ad7-99bc-9fc78eb8ed9c/overview) are solved so I would not remove it from the configuration files.

Doing so, I realised that we still need to add configurations for the ln and lc alignments to the configuration files but I would consider this a task outside this PR.

**Comment by florianesser** [comment]
One other thing I noticed: Is the file `annex-1/mappings/Migration_GID601-AAA-AS712_LN.xlsx` in the right location? Shouldn't it rather be somewhere beneath `annex-2-3/mappings/LandUse`?

> It does not yet run without errors because the ALKIS2INSPIRE_ELU.halex is still missing. It is expected to be added once the tasks for [this project](https://haleconnect.com/#/transformation/org/765/9e2f27b8-5606-4ad7-99bc-9fc78eb8ed9c/overview) are solved so I would not remove it from the configuration files.

Ok, please comment out the corresponding lines in this case, `./gradlew tasks` should always work on `master`.

> Doing so, I realised that we still need to add configurations for the ln and lc alignments to the configuration files but I would consider this a task outside this PR.

Agreed.

**Comment by JohannaOtt** [comment]
> Is the file annex-1/mappings/Migration_GID601-AAA-AS712_LN.xlsx in the right location? Shouldn't it rather be somewhere beneath annex-2-3/mappings/LandUse?

No that is correct. It contains the mapping information for all types from GID 6.0 to 7.1.


> Ok, please comment out the corresponding lines in this case

Done.

**Review by florianesser — APPROVED** [review]
LGTM

**Comment by florianesser** [comment]
@JohannaOtt Can we merge this?

**Comment by JohannaOtt** [comment]
> Can we merge this?

Yes, can be merged - did so now.

**Pull request merged**
